# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dung Lai
tagline:             'blog'
description:         'A personal website of <a href="about" target="_blank">Dung Lai</a>, containing technical blog on technology.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dung Lai
  facebook:          https://facebook.com/dung.lai.733
  email:             tuandunglai@gmail.com
  github:            https://github.com/DungLai

# Custom vars
version:             1.0.0
